name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          mkdir -p public
          # Copy all files and directories needed for the site
          cp -r * public/ || true
          # Ensure index.html is at the root
          cp index.html public/ || true
          # Include .nojekyll file
          cp .nojekyll public/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
